name: GadgetsBits
markdown: kramdown
theme: jekyll-theme-cayman
plugins:
  - jekyll-sitemap
baseurl: /GadgetsBits
url: http://dhanyacm.github.io/GadgetsBits
include: ["_pages"]
permalink: /:title/
permalink: /404.html
